/// Flutter icons CLIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CLIcons
///      fonts:
///       - asset: fonts/CLIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CLIcons {
  CLIcons._();

  static const _kFontFam = 'CLIcons';
  static const String? _kFontPkg = null;

  static const IconData maPage = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bieresCidres = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bio = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boissonsSansAlcool = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boulangeriePain = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cadena = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clickAndCollect = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData epicerie = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fruits = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horticulture = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData legumes = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mesProduits = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mesServices = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ostreiculteur = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData panierFlash = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData panierPermant = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData parametres = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poissonnerie = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData produitsLaitiers = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData produitsMer = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData specialitesSalees = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData specialitesSucrees = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viandes = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vinsSpiritueux = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accueil = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hermine = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rechercheCommerces = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
